#!/bin/bash -xv

: << 'MULTILINE_COMMENT'
# To test from command-line with pragma-git running:
# --------------------------------------------------
#   Terminal 1)
      cd ~/Documents/Projects/Pragma-git/pragma-git
      echo "url=https://github.com/pragma-git/pragma-git.git" | git -c include.path=/Users/jan/Documents/Projects/Pragma-git/pragma-git/gitconfigs/pragma-git-config_dev_mac credential reject # Remove credentials NOTE: Save before
      rm -f /Users/jan/.Pragma-git/.tmp/pragma-askpass-running && touch /Users/jan/.Pragma-git/.tmp/pragma-git-running &&  ./pragma-askpass "Password for https://pragma-git@github.com/pragma-git/pragma-git.git"
#   Terminal 2) 
      rm /Users/jan/.Pragma-git/.tmp/pragma-askpass-running
#   Terminal 1)
      input token
#   Terminal 2) 
      rm /Users/jan/.Pragma-git/.tmp/pragma-askpass-running
      
MULTILINE_COMMENT


# Set variables for different OSes

STARTDIR=$(dirname "$(realpath "$0")") # Script location (folder)

if [ -z ${SYSTEMDRIVE+x} ] ; then
    # Mac or Linux general
    SETTINGSDIR="$HOME/.Pragma-git"
    TMP="$SETTINGSDIR/.tmp"
    
    # Mac or Linux specific
    if [[ "$(uname -s)" == "Darwin" ]]; then
        echo "Mac" > "$TMP/askpasslog.txt"
        INCLUDE_PATH="$STARTDIR/gitconfigs/pragma-git-config_mac"  
    else
        echo "Linux" > "$TMP/askpasslog.txt"
        INCLUDE_PATH="$STARTDIR/gitconfigs/pragma-git-config_linux"  
    fi
    
    env >> "$TMP/askpasslog.txt"
    echo $(pwd) > "$TMP/repo_path"

else
    # Windows specific
    SETTINGSDIR="$USERPROFILE/.Pragma-git"
    TMP="$SETTINGSDIR/.tmp"
    INCLUDE_PATH="$STARTDIR/gitconfigs/pragma-git-config_win" 

    echo "WINDOWS" > "$TMP/askpasslog.txt"
    env >> "$TMP/askpasslog.txt"
    echo $(pwd -W) > "$TMP/repo_path"
fi


# DEV mode
INCLUDE_PATH_DEV="$SETTINGSDIR/pragma-git-config-dev"
if [  -f "$INCLUDE_PATH_DEV" ] ; then
    INCLUDE_PATH="$INCLUDE_PATH_DEV"
fi


# File paths
MAINSIGNALFILE="$TMP/pragma-git-running"    # Pragma-git running (needed to show dialog)
RUNNING="$TMP/pragma-askpass-running"       # Pragma-git looks for this file, and starts askpass
EXIT="$TMP/exit-pragma-askpass"             # Pragma-git closing saves exit-code here, which is transferred to exit code of this script
EXITMESSAGEFILE="$TMP/exit-message-pragma-askpass"  # Message to print to stdout

PRAGMALOG_FILE="$TMP/pragma-git-log.txt"    # Pragma-git log (same as used in javascript PragmaLog function)

mkdir "$TMP" 2>/dev/null


# Log
echo "$(date)" >>  "$PRAGMALOG_FILE" 
echo "$(date) Start pragma-askpass" >>  "$PRAGMALOG_FILE" 
echo "$(date)   Input parameter = $1"  >> "$PRAGMALOG_FILE" 
echo "$(date)   INCLUDE_PATH    = $INCLUDE_PATH"  >> "$PRAGMALOG_FILE" 

# Bail out if pragma-git not running
if [ ! -f "$MAINSIGNALFILE" ] ; then
    echo  " " >> "$TMP/askpass.txt"
    echo  "$(date)   Attempt to open pragma-askpass, but pragma-git not running : $TMP/pragma-git-running)" | tee -a >>  "$PRAGMALOG_FILE" "$TMP/askpass.txt"
    echo  "$(date)   Bail out, require pragma-git to be up" | tee -a >>  "$PRAGMALOG_FILE" "$TMP/askpass.txt"
    exit
fi

# Bail out if askpass already running
if [  -f "$RUNNING" ] ; then
    echo  " " >> "$TMP/askpass.txt"
    echo  "$(date)   Attempt to open pragma-askpass, already open (indicated by existence of file : $TMP/pragma-askpass-running)" | tee -a >>  "$PRAGMALOG_FILE" "$TMP/askpass.txt"
    echo  "$(date)   Bail out, already open (indicated by existence of file : $TMP/pragma-askpass-running)" | tee -a >>  "$PRAGMALOG_FILE" "$TMP/askpass.txt"
    exit
fi

# Store input parameters for Pragma-git/Pragma-askpass to pick them up 
echo "$1" > "$TMP/askpass_first"


# Run Pragma-askpass while $RUNNING exists (removed by Pragma-askpass when closed)
touch "$RUNNING" 
while [  -f "$RUNNING" ]
do
  sleep 1 
done

# Exited Pragma-askpass
EXITCODE=$(cat "$EXIT")
rm "$EXIT"

echo "$(date)   Exit Pragma-askpass GUI with EXITCODE = $EXITCODE" >>  "$PRAGMALOG_FILE" 

# Print to stdout
echo $(cat "$EXITMESSAGEFILE")

# Clean up
rm "$EXITMESSAGEFILE"
rm "$TMP/askpass_first"



# Write to .git/config (if GUI closed with OK)
if [[ "$1" == *"assword"* ]] && [ $EXITCODE -eq 0 ] ; then
    echo "$(date)   Setting .git/config credential.username" >>  "$PRAGMALOG_FILE" 
    
    # username 
    username=$(echo $1 | cut -d/ -f3- | cut -d@ -f1)  # Extract username from "Password for https://pragma-git@github.com/pragma-git/pragma-git.git"
    echo "$(date)     username = $username (from git credential)" | tee -a >>  "$PRAGMALOG_FILE" "$TMP/askpass.txt"
    
    ## replace username in .git/config
    RUN="git -c include.path=\"${INCLUDE_PATH}\" config --local --replace-all \"credential.username\" ${username}"
    echo "$(date)     run: $RUN" | tee -a >>  "$PRAGMALOG_FILE" "$TMP/askpass.txt"
    eval $RUN | tee -a >>  "$PRAGMALOG_FILE" "$TMP/askpass.txt"
    
fi


# Log
echo "$(date) Finish pragma-askpass" >>  "$PRAGMALOG_FILE" 
echo  "$(date) EXIT_CODE = $EXITCODE" >>  "$PRAGMALOG_FILE" 

exit $EXITCODE
