#!/bin/bash 
#
# This script is an askpass program, which is used by pragma-git to show a GUI and interact with git askpass.
#
# It returns username / password to git
# It also adds the username to .git/config, after a succesful password dialog has been used
#

: << 'MULTILINE_COMMENT'

# To force run from command-line with pragma-git running:
# -------------------------------------------------------

#   Start  
      cd ~/Documents/Projects/Pragma-git/pragma-git
      echo "url=https://github.com/pragma-git/pragma-git.git" | git -c include.path=/Users/jan/Documents/Projects/Pragma-git/pragma-git/gitconfigs/pragma-git-config_dev_mac credential reject # Remove credentials NOTE: Save before
      rm -f /Users/jan/.Pragma-git/.tmp/pragma-askpass-running && touch /Users/jan/.Pragma-git/.tmp/pragma-git-running &&  ./pragma-askpass "Password for https://pragma-git@github.com/pragma-git/pragma-git.git"

#   Check file .git/config
      cat .git/config  # Should show:    [credential]
                       #                        username = pragma-git
                       
#   Check for runaway processes
      ps aux | grep askpass

#   Kill runaway processes
      pkill -f askpass
      
MULTILINE_COMMENT


# Set variables for different OSes

STARTDIR=$(dirname "$(realpath "$0")") # Script location (folder)

if [ -z ${SYSTEMDRIVE+x} ] ; then
    # Mac or Linux general
    SETTINGSDIR="$HOME/.Pragma-git"
    TMP="$SETTINGSDIR/.tmp"
    
    # Mac or Linux specific
    if [[ "$(uname -s)" == "Darwin" ]]; then
        echo "Mac" > "$TMP/askpasslog.txt"
        INCLUDE_PATH="$STARTDIR/gitconfigs/pragma-git-config_mac"  
    else
        echo "Linux" > "$TMP/askpasslog.txt"
        INCLUDE_PATH="$STARTDIR/gitconfigs/pragma-git-config_linux"  
    fi
    
    env >> "$TMP/askpasslog.txt"
    echo $(pwd) > "$TMP/repo_path"

else
    # Windows specific
    SETTINGSDIR="$USERPROFILE/.Pragma-git"
    TMP="$SETTINGSDIR/.tmp"
    INCLUDE_PATH="$STARTDIR/gitconfigs/pragma-git-config_win" 

    echo "WINDOWS" > "$TMP/askpasslog.txt"
    env >> "$TMP/askpasslog.txt"
    echo $(pwd -W) > "$TMP/repo_path"
fi


# DEV mode
INCLUDE_PATH_DEV="$SETTINGSDIR/pragma-git-config-dev"
if [  -f "$INCLUDE_PATH_DEV" ] ; then
    INCLUDE_PATH="$INCLUDE_PATH_DEV"
fi


# File paths
MAINSIGNALFILE="$TMP/pragma-git-running"    # Pragma-git running (needed to show dialog)
RUNNING="$TMP/pragma-askpass-running"       # Pragma-git looks for this file, and starts askpass
EXIT="$TMP/exit-pragma-askpass"             # Pragma-git closing saves exit-code here, which is transferred to exit code of this script
EXITMESSAGEFILE="$TMP/exit-message-pragma-askpass"  # Message to print to stdout

PRAGMALOG_FILE="$TMP/pragma-git-log.txt"    # Pragma-git log (same as used in javascript PragmaLog function)

mkdir "$TMP" 2>/dev/null


# Log
echo "$(date)" >>  "$PRAGMALOG_FILE" 
echo "$(date) Start pragma-askpass" >>  "$PRAGMALOG_FILE" 
echo "$(date)   Input parameter = $1"  >> "$PRAGMALOG_FILE" 
echo "$(date)   INCLUDE_PATH    = $INCLUDE_PATH"  >> "$PRAGMALOG_FILE" 

# Bail out if pragma-git not running
if [ ! -f "$MAINSIGNALFILE" ] ; then
    echo  "$(date)   Attempt to open pragma-askpass, but pragma-git not running : $TMP/pragma-git-running)" >>  "$PRAGMALOG_FILE"
    echo  "$(date)   Bail out, require pragma-git to be up" >>  "$PRAGMALOG_FILE"
    exit
fi

# Bail out if askpass already running
if [  -f "$RUNNING" ] ; then
    echo  "$(date)   Attempt to open pragma-askpass, already open (indicated by existence of file : $TMP/pragma-askpass-running)" >>  "$PRAGMALOG_FILE"
    echo  "$(date)   Bail out, already open (indicated by existence of file : $TMP/pragma-askpass-running)" >>  "$PRAGMALOG_FILE"
    exit
fi

# Store input parameters for Pragma-git to pick them up 
echo "$1" > "$TMP/askpass_first"


# Wait for GUI to close ($RUNNING removed by askpass.html when closed)
touch "$RUNNING" 
while [  -f "$RUNNING" ]
do
  sleep 1 
done

# Exited Pragma-askpass
EXITCODE=$(cat "$EXIT")
rm "$EXIT"

echo "$(date)   Exit Pragma-askpass GUI with EXITCODE = $EXITCODE" >>  "$PRAGMALOG_FILE" 

# Print to stdout
echo $(cat "$EXITMESSAGEFILE")

# Clean up
rm "$EXITMESSAGEFILE"
rm "$TMP/askpass_first"


# Write to .git/config (if password GUI closed with OK-button)
if [[ "$1" == *"assword"* ]] && [ $EXITCODE -eq 0 ] ; then
    echo "$(date)   Setting .git/config credential.username" >>  "$PRAGMALOG_FILE" 
    
    # username 
    username=$(echo $1 | cut -d/ -f3- | cut -d@ -f1)  # Extract username from "Password for https://pragma-git@github.com/pragma-git/pragma-git.git"
    echo "$(date)     username = $username (from git credential)" >>  "$PRAGMALOG_FILE"
    
    ## replace username in .git/config
    RUN="git -c include.path=\"${INCLUDE_PATH}\" config --local --replace-all \"credential.username\" ${username}"
    echo "$(date)     run: $RUN" >>  "$PRAGMALOG_FILE"
    eval $RUN >>  "$PRAGMALOG_FILE"
    
fi


# Log
echo "$(date) Finish pragma-askpass" >>  "$PRAGMALOG_FILE" 
echo  "$(date) EXIT_CODE = $EXITCODE" >>  "$PRAGMALOG_FILE" 

exit $EXITCODE
