#!/bin/bash -x
#
# 1) Normally runs on local PC.  
#
# 2) If connected over ssh to a folder, and working with git there, it will start with $5 == 'ssh'
#    Pragma-git will in this case get the files from the server, and open a local pragma-merge ( $5 is not set on the local instance)
#
# 3) For ssh to a folder on Windows, this runs over WSL.  Hence special WSL if statements

LOG_INDENT=""

# Home dir
if [ -z ${SYSTEMDRIVE+x} ]
then
    # Mac or Linux or WSL 
    TMP="$HOME/.Pragma-git/.tmp"
    MERGE_LOG="$TMP/mergelog.txt"
    
    # Modify TMP if run under WSL
    # Windows (git over ssh  is implemented using WSL)
	if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null; then
		TMP="${TMP/\/home/\/mnt\/c\/Users}" # Transform /home/jan/.Pragma-git/.tmp => /mnt/c/Users/jan/.Pragma-git/.tmp 
		
		MERGE_LOG="${TMP}/mergelog.txt"
		LOG_INDENT="   "
		echo ">> PRAGMA-MERGE  $@" >> "$MERGE_LOG"
		echo "${LOG_INDENT}Running in WSL" >> "$MERGE_LOG"
	else
		 # Must be without git over ssh -- restart log
		 echo "Mac or Linux or WSL" > "$MERGE_LOG"
	fi
    
   
    
    #env >> "$MERGE_LOG"
    echo $(pwd) > "$TMP/repo_path"
    echo "${LOG_INDENT}TMP=$TMP" >> "$MERGE_LOG"
else
    # Windows
    TMP="$USERPROFILE/.Pragma-git/.tmp"  # Must be without git over ssh -- restart log
    
    echo "${LOG_INDENT}WINDOWS" > "$MERGE_LOG"
    #env >> "$MERGE_LOG"
    echo $(pwd -W) > "$TMP/repo_path"
    echo "${LOG_INDENT}TMP=$TMP" >> "$MERGE_LOG"
fi



mkdir "$TMP" 2>/dev/null

RUNNING="$TMP/pragma-merge-running"  # Pragma-git looks for this file, and starts Pragma-merge
EXIT="$TMP/exit-pragma-merge"        # Pragma-git closing saves exit-code here, which is transferred to exit code of this script

# SSH folder -- special ($5 == 'ssh' means that pragma-merge is running on server)
echo "${LOG_INDENT}Argument \$5 = $5 (empty if local, 'ssh' if pragma-git from client to ssh folder on this server)" >> "$MERGE_LOG"
if [[ $5 = "ssh" ]] ; then
    FILE_LIST_ON_SSH='/tmp/git_diff_file_list.txt' 
    RUNNING="$TMP/pragma-merge-running-ssh"  # Pragma-git looks for this file, and starts Pragma-merge
    # SSH folder -- special inventory to be picked up from server (this) by client (connecting to here with ssh)
    echo "\"$1\" \"$2\" \"$3\" \"$4\"" > "$FILE_LIST_ON_SSH"  # Store all input parameters for Pragma-git to pick up 
fi

# Bail out if already running
if [  -f "$RUNNING" ] ; then
    echo  " " >> "$MERGE_LOG"
    echo  "${LOG_INDENT}$(date) Attempt to open pragma-merge, already open (indicated by existence of file : $TMP/pragma-merge-running)" >> "$MERGE_LOG"
    echo  "${LOG_INDENT}$(date) Bail out, already open (indicated by existence of file : $TMP/pragma-merge-running)" >> "$MERGE_LOG"
    exit
fi

# If started in WSL -- need to transform to Window file paths in signalling files
if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null; then
	TMP="${TMP/\/home/\/mnt\/c\/Users}" # Transform /home/jan/.Pragma-git/.tmp => /mnt/c/Users/jan/.Pragma-git/.tmp 

	# Rewrite positional parameters $1, .. $4
	set -e -- \
		"$(echo "$1" | sed 's|/mnt/c|C:|')" \
		"$(echo "$2" | sed 's|/mnt/c|C:|')" \
		"$(echo "$3" | sed 's|/mnt/c|C:|')" \
		"$(echo "$4" | sed 's|/mnt/c|C:|')" 

fi


# Local repo : Store input parameters for Pragma-git to pick them up (these are only used on local computer 
echo $1 > "$TMP/first"
echo $2 > "$TMP/second"
echo $3 > "$TMP/third"
echo $4 > "$TMP/fourth"    


# Run Pragma-merge while file $RUNNING exists (removed by Pragma-merge when closed)
echo  " " >> "$MERGE_LOG"

touch "$RUNNING" 
while [  -f "$RUNNING" ]
do
  sleep 1 
done

# Exited Pragma-merge
EXITCODE=$(cat "$EXIT")
# rm "$EXIT"  # Don't remove -- needs this file so I can copy EXITCODE to server (when using ssh-folder)

echo  " " >> "$MERGE_LOG"
echo  "${LOG_INDENT}EXIT pragma-merge" >> "$MERGE_LOG"
echo  "${LOG_INDENT}EXIT_CODE = $EXITCODE" >> "$MERGE_LOG"

echo  " " >> "$MERGE_LOG"

exit $EXITCODE
