name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: Describe_the_bug
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: To_reproduce
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior ( |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error '....')
      placeholder: Tell us how to reproduce
    validations:
      required: true    
  - type: input
    id: repository
    attributes:
      label: Repository
      description: A repository which shows the desribed issue
      placeholder: URL
    validations:
      required: false    
  - type: textarea
    id: Expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what you expected!
    validations:
      required: true
  - type: textarea
    id: System_Info_and_Screen_shots
    attributes:
      label: System Info and Screen shots
      description: Paste info from Pragma-git/Settings/System Info. Attach screen shots and other files describing the issue
      placeholder: System info goes here
    validations:
      required: true   
