name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: Describe the bug
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: To reproduce
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1 . Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      value: "To reproduce"
    validations:
      required: true     
  - type: textarea
    id: Expected behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what you expected!
      value: "The expected behavior"
    validations:
      required: true
  - type: textarea
    id: System Info and Screen shots
    attributes:
      label: System Info and Screen shots
      description: Paste info from Pragma-git/Settings/System Info. Attach screen shots and other files describing the issue
      placeholder: System info goes here
      value: "System info"
    validations:
      required: true   
