#!/bin/bash

# Some good input from https://github.com/Aluxian/nwjs-starter

<< ////

#
# REQUIREMENTS
#

# Install nw-builder

 1) cd ~/Documents/Projects/Pragma-git/pragma-git >
 2) npm install nw-builder --save-dev
 # SKIP? # 3) cd node_modules/nw-builder; npm install


# Prerequisits nw-builder

 4) brew cask install wine-stable --no-quarantine
 
 # SKIP ? # 5) # download rcedit-64.exe (https://github.com/electron/rcedit/releases)  => Hämtade Filer.  
    # Flytta till /Users/jan/Documents/Projects/Pragma-git/pragma-git/make_binaries/rcedit-x64.exe
    chmod a+x /Users/jan/Documents/Projects/Pragma-git/pragma-git/make_binaries/rcedit-x64.exe
    # Högerklicka Öppna efter nedladdning för att tillåta.

 # SKIP ? # 6) rm /Users/jan/Documents/Projects/Pragma-git/pragma-git/node_modules/rcedit/bin/rcedit.exe  \
 # SKIP ? #   ln -s /Users/jan/Documents/Projects/Pragma-git/pragma-git/make_binaries/assets-win/rcedit-x64.exe /Users/jan/Documents/Projects/Pragma-git/pragma-git/node_modules/rcedit/bin/rcedit.exe


# Prerequisits to create installers

 7) brew install makensis # For making windows installer
 8) brew install create-dmg # For creating mac installer
 9) sudo gem install fpm # For linux .deb creation
    run later version : /usr/local/lib/ruby/gems/3.0.0/gems/fpm-1.12.0/bin/fpm  instead of  fpm
 10) brew install gnu-tar # (tar for macos, for fpm)
 11) brew install rpm


# Fix for development on 64-bit Macs
 
  12) # wine64 should be called from wine command (wine fails on 64-bit systems)
      rm /usr/local/bin/wine \
      ln -s /usr/local/bin/wine64 /usr/local/bin/wine


#
# TROUBLE-SHOOTING
#

-  # no windows icons.   5) or 6) above 

# OLD
-  # If install files becomes very large -- then the problem is that  ~/Documents/Projects/Pragma-git/Pragma-git/node_modules/nwjs-builder/caches is included in install.
   # Solution: softlink ~/Documents/Projects/Pragma-git/Pragma-git/node_modules/nwjs-builder/caches -> 
    rm -rf ~/Documents/Projects/Pragma-git/node_modules/nw-builder/cache
    ln -s  ~/Downloads/caches-nw-builder ~/Documents/Projects/Pragma-git/node_modules/nw-builder/cache
   
-  # Not allowed to run rcedit.exe 
   # On Mac, go to "System Settings/Security and Privacy/General" and click "Allow" button.  (Then restart build)

////


    #
    # START OF SCRIPT
    #


    # Declare formatting function (return "[OK] - " or "[XX] - ")
    
    function formatReturn () {
        inCode=$1
        echo -n '['
        
        if [ $inCode -eq 0 ] ; then
            tput setaf 2  # Green
            echo -n "OK"
            tput sgr0  
            echo -n ']   - '
        else
            tput setaf 1  # Red
            echo -n "XX"
            tput sgr0  
            echo -n '] -'
        fi
    }




    COLOR=5
    tput setaf $COLOR; tput setaf $COLOR; echo ' '
    echo '============================'
    echo 'PREPARE ENVIRONMENT'
    echo '============================'
    tput sgr0

    ## Run newer version of fpm
    #export PATH="/usr/local/lib/ruby/gems/3.0.0/gems/fpm-1.12.0/bin:$PATH"
    #export PATH="/usr/local/Cellar/ruby/3.0.0_1/bin:$PATH"
    #which ruby
    #which fpm

    
#
# Install everything in package.json
#    
#
    tput setaf $COLOR; tput setaf $COLOR; echo ' '
    echo '============================'
    echo 'INSTALLING FROM package.json'
    echo '============================'
    tput sgr0
    
	cd /Users/jan/Documents/Projects/Pragma-git/pragma-git/
    npm install
    
     
    tput setaf $COLOR; echo ' '
    echo '=================================='
    echo 'FIX rcedit-x64'
    echo '=================================='
    tput sgr0
    
    rm /Users/jan/Documents/Projects/Pragma-git/pragma-git/node_modules/rcedit/bin/rcedit.exe 
    ln -s /Users/jan/Documents/Projects/Pragma-git/pragma-git/make_binaries/rcedit-x64.exe /Users/jan/Documents/Projects/Pragma-git/pragma-git/node_modules/rcedit/bin/rcedit.exe
    
    # Allow running for file downloaded from internet (TODO : Verify that it works)
    xattr -d com.apple.quarantine '/Users/jan/Documents/Projects/Pragma-git/pragma-git/make_binaries/rcedit-x64.exe'

    echo 'done'
    
#
# Clean folders
#
#
    tput setaf $COLOR; echo ' '
    echo '============================'
    echo 'CLEAN OLD BUILDS'
    echo '============================'
    tput sgr0

    
# Clean old builds
    rm -rf /Users/jan/Documents/Projects/Pragma-git/dist/Pragma-git-*
    rm -rf /Users/jan/Documents/Projects/Pragma-git/dist/mac
    rm -rf /Users/jan/Documents/Projects/Pragma-git/dist/mac_arm64
    rm -rf /Users/jan/Documents/Projects/Pragma-git/dist/win64
    rm -rf /Users/jan/Documents/Projects/Pragma-git/dist/linux64
    
    echo 'done'


#
# Build dists into : "/Users/jan/Documents/Projects/Pragma-git/dist"
#
    tput setaf $COLOR; echo ' '
    echo '=============================='
    echo 'BUILDING FOR ALL PLATFORMS'
    echo '=============================='
    tput sgr0
    
    BUILD_EXIT=0
    
    cd /Users/jan/Documents/Projects/Pragma-git/pragma-git/make_binaries   # Work from here
    
    # Using nw-builder instead :
    DIST='../../dist'
    TEMPDIR="${DIST}/temp_pragma_git"
    CACHEDIR='/Users/jan/Downloads/caches-nwjs'
    
    # Copy everything to temp folder (except .git)
    echo 'Copy from pragma-git repo, exclude .git'
    rsync -a  '/Users/jan/Documents/Projects/Pragma-git/pragma-git/' "${TEMPDIR}" --exclude='.git*' 
    
    # Build for platforms
    node ./scripts/nwbuild_script.js # Build for all platforms and architectures


    # Make pragma-merge and pragma-askpass executables
    echo ' '
    echo 'Make "pragma-merge" executable'
    chmod a+x "../dist/$(ls -1 ../dist/|grep 'mac-x64')/Pragma-git.app/Contents/Resources/app.nw/pragma-merge" || BUILD_EXIT=$?
    
    echo 'Make "pragma-askpass" executable'
    chmod a+x "../dist/$(ls -1 ../dist/|grep 'mac-x64')/Pragma-git.app/Contents/Resources/app.nw/pragma-askpass" || BUILD_EXIT=$?

    echo ' '
    echo $(formatReturn $BUILD_EXIT) Building
#
# Build Mac installer Intel
#
    tput setaf $COLOR; echo ' '
    echo '============================'
    echo 'INSTALLER MACOS 64-BIT INTEL'
    echo '============================'
    tput sgr0
    
    MAC_EXIT=0


    # Copy .app to temporary folder (keep original, to use for apple silicon)
    DIR=$(ls -1 ../dist/|grep  'mac-x64')
    echo "$DIR.dmg" 
    
    # About dialog -- edit plist
    plist="../dist/$DIR/Pragma-git.app/Contents/Info.plist"
    CFBundleVersion=$(git rev-parse --short HEAD) || MAC_EXIT=$?  # Hash as build version (version n.n.n is taken from package.json)
    plutil -replace CFBundleVersion -string "$CFBundleVersion" $plist || MAC_EXIT=$?

    
    # Make installer in destination folder (dist/mac) 
    mkdir ../dist/mac
    cd ../dist/mac

     
    # Make .dmg in ../dist/temp-macos
    test -f Pragma-git-Installer.dmg && rm Pragma-git-Installer.dmg
    create-dmg \
      --volname "Mac-Pragma-git-Installer" \
      --volicon "../../pragma-git/images/icon_installer.icns" \
      --window-pos 200 120 \
      --window-size 500 520 \
      --background "../../pragma-git/make_binaries/assets-mac/dmg_background.png" \
      --icon-size 80 \
      --icon "Pragma-git.app"  125 175 \
      --hide-extension "Pragma-git.app" \
      --app-drop-link 375 175 \
      --add-file  "README.txt" "../../pragma-git/make_binaries/assets-mac/README.txt" 375 335 \
      --icon ".fseventsd"  1000 190 \
      --icon ".VolumeIcon.icns"  1000 190 \
      "$DIR.dmg" \
      "../$DIR/" \
    || MAC_EXIT=$?
    

    # Clean up 
    cd -
    
    echo ' '
    echo $(formatReturn $MAC_EXIT) Creating Mac installer
    
    
    
#
# Build Mac installer Arm
#    
 
    tput setaf $COLOR; echo ' '
    echo '============================'
    echo 'INSTALLER MACOS 64-BIT ARM'
    echo '============================'
    tput sgr0
    
    MAC_EXIT_ARM=0

    # Copy .app to temporary folder (keep original, to use for apple silicon)
    DIR=$(ls -1 ../dist/|grep  'mac-arm64')
    echo "$DIR.dmg"

    # About dialog -- edit plist
    plist="../dist/$DIR/Pragma-git.app/Contents/Info.plist"
    CFBundleVersion=$(git rev-parse --short HEAD) || MAC_EXIT=$?  # Hash as build version (version n.n.n is taken from package.json)
    plutil -replace CFBundleVersion -string "$CFBundleVersion" $plist || MAC_EXIT=$?
    
    # Make installer in destination folder (dist/mac) 
    mkdir ../dist/mac_arm64
    cd ../dist/mac_arm64
    

    # Make .dmg in ../dist/temp-macos
    test -f Pragma-git-Installer.dmg && rm Pragma-git-Installer.dmg
    create-dmg \
      --volname "Mac-Pragma-git-Installer-arm" \
      --volicon "../../pragma-git/images/icon_installer.icns" \
      --window-pos 200 120 \
      --window-size 500 520 \
      --background "../../pragma-git/make_binaries/assets-mac/dmg_background.png" \
      --icon-size 80 \
      --icon "Pragma-git.app"  125 175 \
      --hide-extension "Pragma-git.app" \
      --app-drop-link 375 175 \
      --add-file  "README.txt" "../../pragma-git/make_binaries/assets-mac/README.txt" 375 335 \
      --icon ".fseventsd"  1000 190 \
      --icon ".VolumeIcon.icns"  1000 190 \
      "$DIR.dmg" \
      "../$DIR/" \
    || MAC_EXIT_ARM=$?
    

    # Clean up 
    cd -
    
    echo ' '
    echo $(formatReturn $MAC_EXIT_ARM) "Creating Mac installer (apple silicon)"

# Build Windows installers
#

    tput setaf $COLOR; echo ' '
    echo '===================='
    echo 'INSTALLER WIN 64-BIT'
    echo '===================='
    tput sgr0
    
    WIN_EXIT=0
    
    mkdir ../dist/win64

    DIR=$(ls -1 ../dist/|grep  'win-x64')
    makensis \
    -DEXEFOLDER=$DIR \
    -DOUTPUT="win64/$DIR.exe" \
    -DVERSION="$(echo $DIR | cut -d '-' -f 3)" \
    assets-win/windows_installer.nsi \
    || WIN_EXIT=$?
    
    echo ' '
    echo $(formatReturn $WIN_EXIT) Creating Windows installer

#
# Build Linux DEB installer
#

    tput setaf $COLOR; echo ' '
    echo '============================'
    echo 'INSTALLER LINUX 64-BIT (DEB)'
    echo '============================'
    tput sgr0
    
    DEB_EXIT=0
    
    cd ~/Documents/Projects/Pragma-git/dist
    mkdir linux64
    
    
    DIR=$(ls -1 ../dist/|grep  'linux-x64') # Pragma-git-0.1.0-linux-x64
    VERSION=$(echo $DIR | cut -d '-' -f 3)  # Pragma-git-0.1.0-linux-x64 => VERSION='0.1.0'
    chmod -R a+x "$DIR"

    
    fpm \
    --input-type dir \
    --output-type deb \
    --name 'pragma-git' \
    --architecture 'amd64' \
    --maintainer 'Jan Axelsson <axelsson.jan@gmail.com>' \
    --version "$VERSION" \
    --description "Pragma-git -- the pragmatic revision control"  \
    --license "MIT"  \
    --url "https://pragma-git.github.io"  \
    --deb-no-default-config-files \
    --chdir "$DIR" \
    --package "linux64/$DIR.deb" \
    --depends libatomic1 \
    --depends git \
    --after-install '/Users/jan/Documents/Projects/Pragma-git/pragma-git/make_binaries/assets-linux/postinst' \
    --after-remove '/Users/jan/Documents/Projects/Pragma-git/pragma-git/make_binaries/assets-linux/postrm' \
    .=/opt/pragma-git \
    || DEB_EXIT=$?
    
    echo ' '
    echo $(formatReturn $DEB_EXIT) Creating Linux .deb installer
    
    # Remove installation : sudo dpkg --remove pragma-git
    # Installation : sudo dpkg --install /mnt/Pragma-git/linux64/Pragma-git- (tab)
    


#
# Build Linux RPM installer
#

    tput setaf $COLOR; echo ' '
    echo '============================'
    echo 'INSTALLER LINUX 64-BIT (RPM)'
    echo '============================'
    tput sgr0
    
    RPM_EXIT=0
    
    cd ~/Documents/Projects/Pragma-git/dist
    #mkdir linux64  # Alredady exists
    
    
    DIR=$(ls -1 ../dist/|grep  'linux-x64') # Pragma-git-0.1.0-linux-x64
    VERSION=$(echo $DIR | cut -d '-' -f 3)  # Pragma-git-0.1.0-linux-x64 => VERSION='0.1.0'
    chmod -R a+x "$DIR"
    
    
    # Dependencies are added from problems I had with CentOS7
    fpm \
    --input-type dir \
    --output-type rpm \
    --name 'pragma-git' \
    --architecture 'amd64' \
    --maintainer 'Jan Axelsson <axelsson.jan@gmail.com>' \
    --version "$VERSION" \
    --description "Pragma-git -- the pragmatic revision control"  \
    --license "MIT"  \
    --url "https://pragma-git.github.io"  \
    --chdir "$DIR" \
    --package "linux64/$DIR.rpm" \
    --depends libatomic1 \
    --depends git \
    --rpm-os linux \
    --after-install '/Users/jan/Documents/Projects/Pragma-git/pragma-git/make_binaries/assets-linux/postinst' \
    --after-remove '/Users/jan/Documents/Projects/Pragma-git/pragma-git/make_binaries/assets-linux/postrm' \
    .=/opt/pragma-git \
    || RPM_EXIT=$?
    
    echo ' '
    echo $(formatReturn $RPM_EXIT) Creating Linux .rpm installer
    
    # For a fresh centos 7 install, do  : sudo yum erase libXScrnSaver libatomic pragma-git
    # For centos7 install from file, do : sudo yum localinstall /mnt/Pragma-git/linux64/Pragma-git- (tab)
 
 
 
    tput setaf $COLOR; echo ' '
    echo '========================== ' 
    echo 'Clean up temporary folders '
    echo '========================== ' 
    tput sgr0  
     
    # Temporary folders for MacOS builds
    rm -rf ../dist/Pragma-git-*
    rm -rf temp_pragma_git # Created when building apps
    
    ls -l ../dist/
    
       
#
# DONE
#
    tput setaf $COLOR; echo ' '
    echo '=====' 
    echo 'DONE '
    echo '====='   
    tput sgr0  
    

    
    # Output summary
    echo 'Summary : '
    echo "$(formatReturn $BUILD_EXIT) Building all platforms"
    echo "$(formatReturn $MAC_EXIT) Creating Mac installer (intel)"
    echo "$(formatReturn $MAC_EXIT_ARM) Creating Mac installer (Apple silicon)"
    echo "$(formatReturn $WIN_EXIT) Creating Windows installer"
    echo "$(formatReturn $DEB_EXIT) Creating Linux .deb installer"
    echo "$(formatReturn $RPM_EXIT) Creating Linux .rpm installer"
    echo ' '

    
    read -n 1 -s -r -p "DONE : Press any key to continue" && tput setaf $COLOR; echo ' '
