#!/bin/bash 
# This script closes pragma-merge for ssh on server
# by removing file "$TMP/pragma-merge-running-ssh" from server
#
# Arguments
#   $1      --  SSH URL, for instance  'ssh://jan@localhost/Users/jan/Documents/Projects/Pragma-git/testRepos -- local on ssh/testOnMyMac'
#
# Example :
#   ./ssh-close-pragma-merge-ssh  'ssh://jan@localhost/Users/jan/Documents/Projects/Pragma-git/testRepos -- local on ssh/testOnMyMac'
#

# Import functions and constants: TEMP_FILE_LOCATION, SSH_OPTIONS
source $(dirname $0)/lib/ssh-functions

# Get server info
getSshUrlParts "$1"  # Sets SERVER PORT SERVER_BASE_PATH

FILE_LIST_ON_SSH='/tmp/git_diff_file_list.txt'      # NOTE: this is a remainder -- remember to change in heredoc (between EOFs) -- that is where it matters

# Run git command on remote server 
ssh -T "$SERVER" $SSH_OPTIONS bash -s <<'EOF' 
# quotes around EOF means that following is not expanded

    # Get TMP folder for any system
    if [ -z ${SYSTEMDRIVE+x} ]
    then
        # Mac or Linux  
        TMP="$HOME/.Pragma-git/.tmp"
    else
        # Windows
        TMP="$USERPROFILE/.Pragma-git/.tmp"
    fi
    
    
    
    # Remove signaling file 
    rm -f "$TMP/pragma-merge-running-ssh" 
    
    
    # Verify removal of signaling file
    FILE="$TMP/pragma-merge-running-ssh"    
    if [ -f $FILE ]; then
       echo "File $FILE still exists. IT SHOULD NOT"
       exit 1
    else
       echo "File $FILE removed"
    fi
    
    
    
    
    # Remove file-list file 
    
    FILE_LIST_ON_SSH='/tmp/git_diff_file_list.txt' 
    rm -f "$FILE_LIST_ON_SSH" 
    
    FILE="$FILE_LIST_ON_SSH"
    # Verify removal of file-list file  
    if [ -f $FILE ]; then
       echo "File $FILE still exists. IT SHOULD NOT"
       exit 1
    else
       echo "File $FILE removed"
    fi
    
EOF

# Return error code from ssh
exit $? 
