#!/bin/bash 
# SimpleGit custom Git binary
#
# Implemented as a wrapper to git that runs git commands on remote server over ssh
# and returns stdout and stderr
#
# Works as git, but have  two extra arguments carrying the SSH-URL.  They are removed,
# and standard git arguments remain
#
# Arguments
#   $1      --  -c
#   $2      --  SSH URL, formatted as :  "SSHURL=ssh://jan@home-jan-ubuntu/home/jan/Desktop/ssh_local_test"
#   $opt    --  optional -- -PIPED -- meaning that the command is run as :  echo 'hej' | ssh-git-client ....  -- which is piped into git command on ssh-server
#   $3      --  git command (for instance 'status')
#   $4      --  options to git command
#   $5      --  options to git command
#  .....
# ($1, $2 are example placement for SSHURL, may be anywhere in argument list)
#
# I extract SSH URL and use remaining arguments with git binary 
#
# Example (run git status on remote server) :
#   ./ssh-git-client -c "SSHURL=ssh://jan@home-jan-ubuntu/home/jan/Desktop/ssh_local_test" status
#
# Example on Windows cmd:
#    cd C:\Users\axels\Documents\Projects\Pragma-git\pragma-git\ssh_folder
#	 wsl /mnt/c/Users/axels/Documents/Projects/Pragma-git/pragma-git/ssh_folder/ssh-git-client -c SSHURL=ssh://jan@home-jan-ubuntu/home/jan/Desktop/ssh_local_test version

# Start timing clock
start_time=$(date +%s.%N)

PIPED=false

# Import functions and constants: 
source $(dirname $0)/lib/ssh-functions 

#echo "ALL ARGUMENTS : $@"  >> "$SSH_LOG"

# Get -c SSHURL... from argument list -- also remove these two from total filtered_args argument list

# Remove $SSHURL, and keep remaining arguments
filtered_args=()
while [[ $# -gt 0 ]]; do

    if [[ "$1" == "-c" && "$2" == SSHURL=* ]]; then
		SSHURL="${2#SSHURL=}"
		#echo "SSHURL : $SSHURL" >> "$SSH_LOG"
        # Skip both -c and the SSHURL=... argument
        shift 2
    elif [[ "$1" == "-PIPED" ]]; then
        PIPED=true
        shift
    else
        # Keep the argument
        filtered_args+=("$1")
        shift
    fi
done

REMAINING_ARGUMENTS="${filtered_args[@]}" 
echo ">> SSH_GIT_CLIENT  ${REMAINING_ARGUMENTS} " >> "$SSH_LOG"

SCRIPT_FOLDER=$(dirname $0)   # The location of this script is the same as "pragma-merge" command

# Get server info
getSshUrlParts "$SSHURL"  # Sets SERVER PORT SERVER_BASE_PATH


# Fix quotes around  --pretty statement, sent from simpleGit (--pretty=format:òòòòòò %H ò %aI ò %s ò %D ò %b ò %aN ò %aE òò )
REMAINING_ARGUMENTS=$(echo ${REMAINING_ARGUMENTS}| sed "s/òòòòòò/'òòòòòò/g" | sed "s/ òò/ òò'/g")

# Git command running from $SERVER_BASE_PATH
COMMAND="git -C \"${SERVER_BASE_PATH}\" ${REMAINING_ARGUMENTS}"

# Start Pragma-merge in new thread
case "${filtered_args[2]}"  in
mergetool|difftool)
    echo "    Calling  ssh_folder/delayed-start-pragma-merge " >> "$SSH_LOG"
    "${SCRIPT_FOLDER}/delayed-start-pragma-merge" "$SSHURL" >> "$SSH_LOG"  & 
;;
mergetool)

;;
esac


# Run git command on remote server 
if [ "$PIPED" = true ]; then
    ssh -T "$SERVER" -p "${PORT}" $SSH_OPTIONS "bash -c '$COMMAND'" < /dev/stdin
else
    ssh -T "$SERVER"  -p ${PORT} $SSH_OPTIONS bash -s <<EOF
        $COMMAND
EOF

fi

SSH_RETURN_STATUS=$?

# Calculate timing
end_time=$(date +%s.%N)
time_diff=$(awk "BEGIN {print $end_time - $start_time }")
{
    echo "    $time_diff -- ssh -T \"$SERVER\"  -p ${PORT} $SSH_OPTIONS"  
    echo "    $time_diff -- ${COMMAND}" 
    echo ' '
} >> "$SSH_LOG"


exit $SSH_RETURN_STATUS  
