#!/bin/bash
# SimpleGit custom Git binary
#
# Implemented as a wrapper to git that runs git commands on remote server over ssh
# and returns stdout and stderr
#
# Works as git, but have an extra second argument
#
# Arguments
#   $1      --  SSH URL, for instance 'ssh://jan@linus/usr/local/MATLAB/imlook4d/imlook4d_DEVELOP'
#   $2      --  git command (for instance 'status')
#   $3      --  options to git command
#   $4      --  options to git command
#  .....
#
# All arguments except $1 are standard used in simpleGit.  
# So I extract SSH URL from $1 and use remaining arguments with git binary
#
# Example (run git status on remote server) :
#   ./ssh-git-client 'ssh://jan@localhost/Users/jan/Documents/Projects/Pragma-git/testRepos -- local on ssh/testOnMyMac' status
#

# Start timing clock
start_time=$(date +%s.%N)


# Import functions and constants: 
source $(dirname $0)/lib/ssh-functions 

SCRIPT_FOLDER=$(dirname $0)   # The location of this script is the same as "pragma-merge" command

# Get server info
getSshUrlParts "$1"  # Sets SERVER PORT SERVER_BASE_PATH

# Remove SSH URL, and keep remaining arguments
shift
REMAINING_ARGUMENTS="$@"
# Fix quotes around  --pretty statement, sent from simpleGit (--pretty=format:òòòòòò %H ò %aI ò %s ò %D ò %b ò %aN ò %aE òò )
REMAINING_ARGUMENTS=$(echo ${REMAINING_ARGUMENTS}| sed "s/òòòòòò/'òòòòòò/g" | sed "s/ òò/ òò'/g")

# Git command running from $SERVER_BASE_PATH
COMMAND="git -C \"${SERVER_BASE_PATH}\" ${REMAINING_ARGUMENTS}"

# Start Pragma-merge in new thread
case "$3" in
mergetool|difftool)
    echo "Calling  ssh_folder/delayed-start-pragma-merge " >> "$SSH_LOG"
    "${SCRIPT_FOLDER}/delayed-start-pragma-merge" "$SSH_REPO_URL" >> "$SSH_LOG"  & 
;;
mergetool)

;;
esac


# Run git command on remote server 
ssh -T "$SERVER"  -p ${PORT} $SSH_OPTIONS bash -s <<EOF
    $COMMAND
EOF

SSH_RETURN_STATUS=$?

# Calculate timing
end_time=$(date +%s.%N)
time_diff=$(echo "$end_time - $start_time" | bc)
{
    echo "$time_diff -- ssh -T \"$SERVER\"  -p ${PORT} $SSH_OPTIONS"  
    echo "$time_diff -- ${COMMAND} \n" 
    echo ' '
} >> "$SSH_LOG"


exit $SSH_RETURN_STATUS  
