#!/bin/bash 
# This script closes pragma-merge for ssh on server
# by removing file "$TMP/pragma-merge-running-ssh" from server
#
# Arguments
#   $1      --  SSH URL, for instance  'ssh://jan@localhost/Users/jan/Documents/Projects/Pragma-git/testRepos -- local on ssh/testOnMyMac'
#
# Example :
#   ./ssh-close-pragma-merge-ssh  'ssh://jan@localhost/Users/jan/Documents/Projects/Pragma-git/testRepos -- local on ssh/testOnMyMac'
#


# Import functions and constants: TEMP_FILE_LOCATION, SSH_OPTIONS
source $(dirname $0)/lib/ssh-functions

echo ">> SSH-CLOSE-PRAGMA-MERGE-SSH  \"$1\"" >> "$MERGE_LOG"

# Platform specific $TMP in Home dir
if [ -z ${SYSTEMDRIVE+x} ]
then
    # Mac or Linux or WSL
    TMP="$HOME/.Pragma-git/.tmp"
    
    # Modify TMP if run under WSL
    # Windows (git over ssh  is implemented using WSL)
	if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null; then
		TMP="${TMP/\/home/\/mnt\/c\/Users}" # Transform /home/jan/.Pragma-git/.tmp => /mnt/c/Users/jan/.Pragma-git/.tmp 
		MERGE_LOG="${TMP}/ssh-log.log"
	fi
else
    # Windows local
    TMP="$USERPROFILE/.Pragma-git/.tmp"
fi

echo  "SSH-CLOSE-PRAGMA-MERGE $1"  >> "$MERGE_LOG"
echo  " "  >> "$MERGE_LOG"

# Get server info
getSshUrlParts "$1"  # Sets SERVER PORT SERVER_BASE_PATH

FILE_LIST_ON_SSH='/tmp/git_diff_file_list.txt'  

# Get EXIT CODE (local) 
EXITCODE=$(cat "$TMP/exit-pragma-merge")

# Run git command on remote server 
ssh -T "$SERVER" $SSH_OPTIONS bash -s <<EOF
# \$ means that a variable name is on server ($ means that the variable is inserted from above script)

    #
    # Get TMP folder for any system (Really - ssh-folder only works on Linux / Mac - so this is a bit unnecessary)
    #
        if [ -z \${SYSTEMDRIVE+x} ]
        then
            # Mac or Linux  
            TMP="\$HOME/.Pragma-git/.tmp"
        else
            # Windows
            TMP="\$USERPROFILE/.Pragma-git/.tmp"
        fi
        
    #
    # Copy EXIT status from local to server
    #
        echo $EXITCODE > "\$TMP/exit-pragma-merge"


    
    #
    # Remove signaling file (remote pragma-merge will terminate, and use above EXITCODE from file)
    #
        rm -f "\$TMP/pragma-merge-running-ssh" 
        
        # Verify removal of signaling file
        FILE="\$TMP/pragma-merge-running-ssh"    
        if [ -f \$FILE ]; then
           echo "File \$FILE still exists. IT SHOULD NOT"
           exit 1
        else
           echo "File \$FILE removed"
        fi

    
    #
    # Remove file-list file 
    #
        rm -f "$FILE_LIST_ON_SSH" 
        
        FILE="$FILE_LIST_ON_SSH"
        # Verify removal of file-list file  
        if [ -f \$FILE ]; then
           echo "File \$FILE still exists. IT SHOULD NOT"
           exit 1
        else
           echo "File \$FILE removed"
        fi
        
EOF

# Clean up local

	# Make signal file to close Pragma-merge
	echo  "    rm -f $TMP/exit-pragma-merge"  >> "$MERGE_LOG"
    rm -f "$TMP/exit-pragma-merge"
	EXIT_CODE=$?
	
	
	echo  "    EXIT_CODE = $EXITCODE"  >> "$MERGE_LOG"
	echo  " "  >> "$MERGE_LOG"
	
# Return exit code from ssh
exit $EXIT_CODE
