#!/bin/bash

# Link to the binary
ln -sf /opt/pragma-git/Pragma-git /usr/local/bin/pragma-git # Official name
ln -sf /opt/pragma-git/Pragma-git /usr/local/bin/pragmagit  # Misspelling options
ln -sf /opt/pragma-git/Pragma-git /usr/local/bin/Pragma-git
ln -sf /opt/pragma-git/Pragma-git /usr/local/bin/Pragmagit

# Icons
cp '/opt/pragma-git/images/linux-icons/48/pragma-git.png' '/usr/share/icons/hicolor/48x48/apps'
cp '/opt/pragma-git/images/linux-icons/256/pragma-git.png' '/usr/share/icons/hicolor/256x256/apps'
cp '/opt/pragma-git/images/linux-icons/scalable/pragma-git.svg' '/usr/share/icons/hicolor/scalable/apps'

# Set executable
chmod -R 755 /opt/pragma-git # Make executable for all users (and writable for root)

# Launcher icon, all users
desktop-file-install \
    --dir=/usr/share/applications \
    /opt/pragma-git/make_binaries/assets-linux/pragma-git.desktop
